# Generated by Django 5.2.17 on 2026-09-08 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='observación')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de cumplimiento')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='chores.chore', verbose_name='tarea')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_completions', to=settings.AUTH_USER_MODEL, verbose_name='realizada por')),
            ],
            options={
                'verbose_name': 'cumplimiento',
                'verbose_name_plural': 'cumplimientos',
                'ordering': ('-completed_at',),
            },
        ),
    ]
