# Generated by Django 5.2.17 on 2026-09-08 04:14

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_recurrence_anchor(apps, schema_editor):
    Chore = apps.get_model("chores", "Chore")
    for chore in Chore.objects.filter(recurrence_anchor_day__isnull=True).iterator():
        chore.recurrence_anchor_day = chore.next_due_date.day
        chore.save(update_fields=["recurrence_anchor_day"])


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='recurrence_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día ancla de recurrencia'),
        ),
        migrations.RunPython(populate_recurrence_anchor, migrations.RunPython.noop),
        migrations.AddField(
            model_name='completion',
            name='scheduled_for',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha programada'),
        ),
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.UniqueConstraint(fields=('chore', 'scheduled_for'), name='one_completion_per_occurrence'),
        ),
    ]
